/**
 * Project Euler in Java
 * @Author MatthewLQM
 *
 * Problem 1 Even Fibonacci numbers
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
public class Problem2 {
    public static void main(String[] argv) {
        int number1 = 1, number2 = 2, temp = 3, result = 2;
        while(temp < 4000000) {
            if(temp % 2 == 0) result += temp;
            number1 = number2;
            number2 = temp;
            temp = number1 + number2;
        }
        System.out.println("The result is " + result);
    }
}
